[gcp_service_account]
type = "service_account"
project_id = "rdna-461214"
private_key_id = "352ca5cd245ec8eb63229e20f1f0ce47d6dd41b9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClMSYA540n2VGU
I5gpyqWf5FN/kXdc7Gyu4J9six1yqIAwUFOhdPslo9HNcKZjWtP4wUR3T/WE8lnu
2TH2svRlOp7D72JgI4oMoPv5bu+QGpWM2/a9ma8+JWnEVUiKEN2FD2+qiZvhSNNi
tJbhOPdFquw+7VpYtOXV3+GgF53dtdVut5pj0xl6TyCIGO3PbPsdvuSbJXaf3/yv
tZmQ567J4NG62qPyw0Pe83QpPij838R6Yby1R0OKplC2WJwiiKVpbCkPEhgX8DTF
qzZAmMnAXawpidw0ahCx7WqrgPuO5hVWdWTUaetC2G8W/G96NuE+CoUL07Js/cBv
JqyGp1WpAgMBAAECggEABReOQIHiuoM66LJDhapET7jwj/fyciVW4PnLQEPLh8DE
7s2oaPYxAFiGkOrI3jrVr48kO/n1gKsdyucxYJWPQ12QDkx0lQUTbiSPj9aea4E+
RztykCagHcN2eVcC/OqHLDZXxAMo5cQNFreoB6TuDlzgmmdOR89lCaI0k27sRAIY
Sdf3bx3UvlJPPx/wz+1grkUf4r9kk4qURvJ3VuPq+FA9E5gMkH6s55XRYPh5tanx
s1ggHJRrFggakqM9Y9sD9TEip0DqWtXSwZoAsMaQOKAKEaYgaCEycFXs0ZrnGmTb
y/U/FCW9cH3aYySLrHcE1F6k+S8zA1H/22fjv4diQQKBgQDn97Y+dAUKt0nTgJA+
Krnk3/07bJal87bC4zxfx90JE8RAtC686MPGem+/IHxWixR7mxWnB5VCtHVwMh7t
86QoAbaFVy35xvxd+VNWjtRysyRnQeMu7r1wgKCKstAGGDFKBDVg2lwf/pPDxeVH
SA40AgejNv5l0cHCyr4pVoeZEQKBgQC2TmaYmuN4aF2Ifdj+ZZbFmyeBMjKQAqEV
9EEtnfc2kVtZpgemgsFILbM2IKmom8hzWdwRXXSLCJow6YrXrDDHeBZOUlXsH6KO
aDiUIffqmIWS1hitc23TgszICcqzBg4Wjd4N+uvyu392aSeyR5JYycZD9Qp/YJTd
K80BOTszGQKBgH9ci6xoqSgEEL3WtdvcO6rFrNVGvsQpNux0NX7lTqAgQT3BcHP6
XRuJt/c5j+s4e6uOL+pAiJxSVrSeYEsH3da1chBuGGku7vtt3GsHCvBbGZ60F1d6
b3rotLzShtMBz3YzL1eZLMHIVjtEWam0j0/Q2X6swCsJaxhXluc9gj/xAoGBAJ28
7laCRelL3AoaYaOUQMVPvvmxdkBWlgyJ389Zi6oiUPkbiCkRn60VJafi0Qk7aVAt
YxV/WDRoSAmkOObtbPNaO2qfIQsCQEOZd8LsNTc9qu1m48lIQ7GrzgYTOth1l8D6
FTThdD/87YeF6rv942mBhFQOdHvMFGHd4S5613cZAoGBAOUbAqEulUo6TbMogxsI
WZSIp4HJYj6RQi5x79r9vk8oybdiuKzsmKdngdPnsxgseYs12uZEHjixtzVxZESc
q9hPRjbnh1sftpooqFuWM6mdbL/SOwxLf12rdOzcGh0RMdYpWvHSGTXr4w1R/bkb
WVRAKqtYXBgM5YJq3xPYBp8u
-----END PRIVATE KEY-----"""
client_email = "streamlit-drive@rdna-461214.iam.gserviceaccount.com"
client_id = "105183925195707560570"
token_uri = "https://oauth2.googleapis.com/token"

[drive]
folder_id = "1fHtt2LWw0SRx8EUemXHoZQWd0lw3wZXe" 

[github]
token = "ghp_SEU_TOKEN"           # coloque seu GitHub Token aqui se quiser auto-upload
repo = "usuario/repositorio"      # ex.: dapsat100-star/form1
branch = "main"
base_path = "reports"
